# Generated by Django 3.1.7 on 2021-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210228_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
